### PR TITLE
Unknown person portrait option

### PR DESCRIPTION
**Pull request by a2line**
This option to have a default image when it is missing was requested on mailing list, images comes from KDE:
https://commons.wikimedia.org/wiki/File:Crystal_Clear_kdm_user_female.png
https://commons.wikimedia.org/wiki/File:Crystal_Clear_kdm_user_male.png
https://commons.wikimedia.org/wiki/File:Crystal_Clear_app_Login_Manager.png

### CODE REVIEW

**Comment by mbouaziz** [comment]
Having images when unknown as an option -> good. Wasn't it working before?
Changing the images to wikimedia ones -> why not.

I don't like your choice for img_unknown_u_man.png, it looks like a couple, not like someone with unknown gender.

**Comment by a2line** [comment]
I have added a question mark on that image.

**Comment by ipfix** [comment]
What the status of this PR ? Should it be merged ?
I like the hair in the picture, looks like a playmobile helmet :)

**Comment by a2line** [comment]
Yes, this one could be merged too (instead of playing with playmobils!)

**Comment by ipfix** [comment]
Merged.

**Pull request closed without merging**
